title: Website PPW
author: Achmad Hakim Abdul Chanan
html:
  use_repository_button: true
  use_download_button: true
  extra_navbar: |
    Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
